spring:
  application:
    name: facebook
  datasource:
    url: jdbc:mysql://localhost:3306/face
    username: root
    password: ali45
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ali.bn.rabee@gmail.com
    password: sdnt hnwq xdxu adjd
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          from: noreply@sapp.com
        transport:
          protocol: smtp
    default-encoding: UTF-8
    test-connection: false


app:
  root:
    backend: http://localhost:8080

upload:
  user:
    images: uploads/user
  post:
    images: uploads/post

jwt:
  secret: d16baa1b9e8bee8cd146d5d733fdb58ad7a2d21b1fa2022e387415c03c6b5ee4

logging:
  file:
    name: log/log.log